version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "04:34"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "rubocop-lts"
      - dependency-name: "appraisal"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
