inherit_from:
  - .rubocop_todo.yml
  - lib/rspec/block_is_expected/rubocop.yml

require:
  - rubocop-lts
  - rubocop-md
  - rubocop-rake
  - rubocop-rspec

inherit_gem:
  rubocop-lts: rubocop-lts.yml

AllCops:
  DisplayCopNames: true # Display the name of the failing cops
  Exclude:
    - 'gemfiles/vendor/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe
    - it
    - shared_context
    - shared_examples
    - shared_examples_for
    - namespace
    - draw

Layout/LineLength:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Lambda:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# Enable when drop support for Ruby < 2
Style/ExpandPathArguments:
  Enabled: false

RSpec/FactoryBot/CreateList:
  Enabled: false
