AllCops:
  DisplayCopNames: true # Display the name of the failing cops
  Exclude:
    - 'gemfiles/vendor/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - it
    - shared_context
    - shared_examples
    - shared_examples_for
    - namespace
    - draw

Metrics/LineLength:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Lambda:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# Enable when drop support for Ruby < 2
Style/ExpandPathArguments:
  Enabled: false
