inherit_gem:
  rubocop-lts: config/rubygem_rspec.yml

RSpec/InstanceVariable:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false
