env:
  global:
  - JRUBY_OPTS="-Xcli.debug=true --debug"
  - CC_TEST_REPORTER_ID=b371af9d80b8b1f593e87d11c20137cf7573149a6296278715acd3fa48ddc280

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- bundle exec rspec

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install:
- gem update --system
- gem install bundler

install:
- bundle install

bundler_args: --no-deployment --jobs 3 --retry 3

cache: bundler

language: ruby
sudo: false
matrix:
  allow_failures:
  - rvm: jruby-head
  - rvm: ruby-head
  fast_finish: true
  include:
  - rvm: 1.8.7-p371
    gemfile: gemfiles/ruby_1.8.7_p371.gemfile
  - rvm: 1.9.3-p551
    gemfile: gemfiles/ruby_1.9.3_p551.gemfile
  - rvm: 2.0.0-p648
    gemfile: gemfiles/ruby_2.0.0_p648.gemfile
  - rvm: 2.1.10
    gemfile: gemfiles/ruby_2.1.10.gemfile
  - rvm: 2.2.10
    gemfile: gemfiles/ruby_2.2.10.gemfile
  - rvm: 2.3.7
    gemfile: gemfiles/ruby_2.3.7.gemfile
  - rvm: 2.4.4
    gemfile: gemfiles/ruby_2.4.4.gemfile
  - rvm: 2.5.1
    gemfile: gemfiles/ruby_2.5.1.gemfile
  - rvm: ruby-head
    gemfile: gemfiles/ruby_head.gemfile
  - rvm: jruby-1.7.26
    gemfile: gemfiles/jruby_1.7.26.gemfile
  - rvm: jruby-9.1.9.0
    gemfile: gemfiles/jruby_9.1.9.0.gemfile
  - rvm: jruby-9.2.0.0
    gemfile: gemfiles/jruby_9.2.0.0.gemfile
  - rvm: jruby-head
    gemfile: gemfiles/jruby_head.gemfile
